### ISSUE TITLE
Issue 5 :: Checklist before official launch

### ISSUE THREAD

**Issue by wenqili** [wenqili/adjacent#40]
- [x] All the articles: unchecked comments and sharing.
- [ ] All the articles: has a title, authors, illustration authors, high res featured images on the home page.
- [ ] All the articles: has a hero banner image, blurb and consistent author bio inside articles.
- [ ] All the articles: interactive illustration are working on cross platforms, or if not, add a note.
- [x] Articles order are right.
- [x] Up to date Editorial Board
- [x] Pass a11y checker.
